// Greek license plate region mapping - OFFICIAL DATA
// Source: Wikipedia - Πινακίδες κυκλοφορίας οχημάτων της Ελλάδας
// First two letters map to Greek regions

// Latin to Greek character mapping (for user convenience)
const latinToGreek: Record<string, string> = {
  A: 'Α',
  a: 'Α',
  B: 'Β',
  b: 'Β',
  E: 'Ε',
  e: 'Ε',
  Z: 'Ζ',
  z: 'Ζ',
  H: 'Η',
  h: 'Η',
  I: 'Ι',
  i: 'Ι',
  K: 'Κ',
  k: 'Κ',
  M: 'Μ',
  m: 'Μ',
  N: 'Ν',
  n: 'Ν',
  O: 'Ο',
  o: 'Ο',
  R: 'Ρ',
  r: 'Ρ',
  T: 'Τ',
  t: 'Τ',
  Y: 'Υ',
  y: 'Υ',
  X: 'Χ',
  x: 'Χ',
  // Handle Greek lowercase to uppercase
  α: 'Α',
  β: 'Β',
  ε: 'Ε',
  ζ: 'Ζ',
  η: 'Η',
  ι: 'Ι',
  κ: 'Κ',
  μ: 'Μ',
  ν: 'Ν',
  ο: 'Ο',
  ρ: 'Ρ',
  τ: 'Τ',
  υ: 'Υ',
  χ: 'Χ',
};

// Convert Latin characters to Greek
const convertLatinToGreek = (text: string): string => {
  return text
    .split('')
    .map((char) => latinToGreek[char] || char)
    .join('');
};

export const greekRegions: Record<string, string> = {
  ΥΑ: 'Athens',
  ΥΒ: 'Athens',
  ΥΕ: 'Athens',
  ΥΖ: 'Athens',
  ΥΗ: 'Athens',
  ΥΙ: 'Piraeus',
  ΥΚ: 'Piraeus',
  ΥΜ: 'Piraeus',
  ΥΝ: 'Piraeus',
  ΥΟ: 'West Attica',
  ΥΡ: 'West Attica',
  ΥΤ: 'West Attica',
  ΥΥ: 'East Attica',
  ΥΧ: 'East Attica',
  ΖΖ: 'Athens',
  ΖΗ: 'Athens',
  ΖΚ: 'Athens',
  ΖΜ: 'Athens',
  ΖΝ: 'Piraeus',
  ΖΡ: 'Piraeus',
  ΖΤ: 'West Attica',
  ΖΥ: 'East Attica',
  ΖΧ: 'East Attica',
  ΖΕ: 'Athens',
  ΖΙ: 'Athens',
  ΖΟ: 'Athens',
  ΙΒ: 'Athens',
  ΙΕ: 'Athens',
  ΙΖ: 'Athens',
  ΙΗ: 'Athens',
  ΙΚ: 'Athens',
  ΙΜ: 'Athens',
  ΙΟ: 'Athens',
  ΙΡ: 'Athens',
  ΙΤ: 'Athens',
  ΙΥ: 'Athens',
  ΙΝ: 'Ioannina',
  ΙΙ: 'Ioannina',
  ΧΕ: 'Athens',
  ΧΖ: 'Athens',
  ΧΗ: 'Athens',
  ΧΡ: 'Athens',
  ΧΤ: 'Athens',
  ΧΥ: 'Athens',
  ΧΧ: 'Athens',
  ΧΜ: 'Athens',
  ΗΒ: 'Athens',
  ΟΑ: 'Athens',
  ΟΒ: 'Athens',
  ΟΕ: 'Athens',
  ΟΖ: 'Athens',
  ΟΗ: 'Athens',
  ΟΙ: 'Athens',
  ΟΚ: 'Athens',
  ΟΜ: 'Athens',
  ΟΝ: 'Athens',
  ΟΟ: 'Athens',
  ΟΤ: 'Athens',
  ΟΥ: 'Athens',
  ΟΧ: 'Athens',
  ΒΕ: 'Piraeus',
  ΒΖ: 'Piraeus',
  ΒΗ: 'Piraeus',
  ΒΧ: 'Piraeus',
  ΒΝ: 'West Attica',
  ΒΡ: 'West Attica',
  ΒΚ: 'East Attica',
  ΒΜ: 'East Attica',
  ΒΙ: 'Boeotia',
  ΒΥ: 'Boeotia',
  ΒΟ: 'Magnesia',
  ΒΒ: 'Magnesia',
  ΒΑ: 'Magnesia',
  ΒΤ: 'Magnesia',
  ΤΖ: 'Piraeus',
  ΤΗ: 'Aetoloacarnania',
  ΤΜ: 'Argolida',
  ΤΡ: 'Arcadia',
  ΤΚ: 'Trikala',
  ΤΝ: 'Trikala',
  ΤΙ: 'Pieria',
  ΤΟ: 'Drama',
  ΤΕ: 'Corfu',
  ΤΒ: 'Corfu',
  ΤΧ: 'Preveza',
  ΤΥ: 'Chania',
  ΑΙ: 'Aetoloacarnania',
  ΑΡ: 'Argolida',
  ΑΤ: 'Arta',
  ΑΧ: 'Achaia',
  ΑΖ: 'Achaia',
  ΑΟ: 'Achaia',
  ΑΑ: 'Achaia',
  ΑΥ: 'Achaia',
  ΑΒ: 'Kavala',
  ΑΚ: 'Laconia',
  ΑΜ: 'Phocida',
  ΑΝ: 'Lasithi',
  ΑΕ: 'Lasithi',
  ΑΗ: 'Xanthi',
  ΕΗ: 'Evia',
  ΕΙ: 'Evia',
  ΕΒ: 'Evros',
  ΕΑ: 'Dodecanese',
  ΕΜ: 'Cyclades',
  ΕΖ: 'Cyclades',
  ΕΝ: 'Cyclades',
  ΕΟ: 'Cyclades',
  ΕΕ: 'Pella',
  ΕΤ: 'Corfu',
  ΕΥ: 'Lefkada',
  ΕΧ: 'Kilkis',
  ΕΡ: 'Serres',
  ΡΝ: 'Grevena',
  ΡΜ: 'Drama',
  ΡΟ: 'Dodecanese',
  ΡΚ: 'Dodecanese',
  ΡΥ: 'Dodecanese',
  ΡΧ: 'Dodecanese',
  ΡΙ: 'Larissa',
  ΡΡ: 'Larissa',
  ΡΤ: 'Larissa',
  ΡΖ: 'Preveza',
  ΡΕ: 'Rethymno',
  ΡΗ: 'Rethymno',
  ΡΑ: 'Florina',
  ΡΒ: 'Corinthia',
  ΜΕ: 'Aetoloacarnania',
  ΜΑ: 'Chalkidiki',
  ΜΒ: 'Samos',
  ΜΟ: 'Samos',
  ΜΙ: 'Phthiotida',
  ΜΚ: 'Karditsa',
  ΜΜ: 'Pella',
  ΜΝ: 'Kozani',
  ΜΧ: 'Evros',
  ΜΥ: 'Lesbos',
  ΜΤ: 'Lesbos',
  ΜΗ: 'Limnos',
  ΜΖ: 'Messinia',
  ΜΡ: 'Laconia',
  ΝΑ: 'Thessaloniki',
  ΝΒ: 'Thessaloniki',
  ΝΕ: 'Thessaloniki',
  ΝΖ: 'Thessaloniki',
  ΝΗ: 'Thessaloniki',
  ΝΙ: 'Thessaloniki',
  ΝΚ: 'Thessaloniki',
  ΝΜ: 'Thessaloniki',
  ΝΝ: 'Thessaloniki',
  ΝΟ: 'Thessaloniki',
  ΝΡ: 'Thessaloniki',
  ΝΤ: 'Thessaloniki',
  ΝΥ: 'Thessaloniki',
  ΝΧ: 'Thessaloniki',
  ΚΗ: 'Evrytania',
  ΚΖ: 'Kozani',
  ΚΒ: 'Kavala',
  ΚΕ: 'Cephalonia',
  ΚΙ: 'Kilkis',
  ΚΚ: 'Rhodope',
  ΚΟ: 'Rhodope',
  ΚΡ: 'Corinthia',
  ΚΤ: 'Kastoria',
  ΚΥ: 'Corfu',
  ΚΑ: 'Karditsa',
  ΚΧ: 'Dodecanese',
  ΚΜ: 'Messinia',
  ΚΝ: 'Pieria',
  ΗΑ: 'Ileia',
  ΗΕ: 'Ileia',
  ΗΜ: 'Imathia',
  ΗΧ: 'Imathia',
  ΗΡ: 'Heraklion',
  ΗΚ: 'Heraklion',
  ΗΖ: 'Heraklion',
  ΗΗ: 'Heraklion',
  ΗΙ: 'Heraklion',
  ΗΤ: 'Heraklion',
  ΗΝ: 'Thesprotia',
  ΗΥ: 'Phthiotida',
  ΗΟ: 'Xanthi',
  ΧΑ: 'Evia',
  ΧΙ: 'Chios',
  ΧΟ: 'Chios',
  ΧΝ: 'Chania',
  ΧΒ: 'Chania',
  ΧΚ: 'Chalkidiki',
  ΟΡ: 'Evros',
};

export const lookupPlateRegion = (plate: string): string | null => {
  // Remove special characters
  const cleanPlate = plate.replace(/[-\s]/g, '');

  // Convert Latin characters to Greek if needed
  const greekPlate = convertLatinToGreek(cleanPlate);

  // Extract first 2 letters (the region code)
  const regionCode = greekPlate.substring(0, 2);

  return greekRegions[regionCode] || null;
};

// Get all available regions
export const getAllRegions = (): string[] => {
  const regions = new Set<string>();
  Object.values(greekRegions).forEach((region) => regions.add(region));
  return Array.from(regions).sort();
};

// Get all plate codes for a specific region
export const getPlateCodesForRegion = (region: string): string[] => {
  return Object.entries(greekRegions)
    .filter(([_, value]) => value === region)
    .map(([code]) => code);
};
